export const investmentProducts =  [
        {
            id:1,
            name: "AngloGold Ashanti Depositary Shares",
            symbol: "AADS",
            price: 0.4,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },

        {
            id:2,
            name: "Access Bank Ghana",
            symbol: "ACCESS",
            price: 4,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
        {
             id:3,
            name: "Agricultural Development Bank",
            symbol: "ADB",
            price: 5.06,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
        {
            id:4,
            name: "AngloGold Ashanti Limited",
            symbol: "AGA",
            price: 37,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
        {
            id:5,
            name: "Aluworks Limited",
            symbol: "ALW",
            price: 0.09,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
        {
            id:6,
            name: "Ayrton Drugs Manufacturing Co.",
            symbol: "AYRTN",
            price: 0.08,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
        {
            id:7,
            name: "Benso Oil Palm Plantation Limited",
            symbol: "BOPP",
            price: 4.13,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
        {
            id:8,
            name: "CAL Bank Limited",
            symbol: "CAL",
            price: 0.82,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
        {
            id:9,
            name: "Clydestone Ghana Limited",
            symbol: "CLYD",
            price: 0.03,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
        {
            id:10,
            name: "Camelot Ghana Limited",
            symbol: "CMLT",
            price: 0.1,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
        {
            id:11,
            name: "Cocoa Processing Company Limited",
            symbol: "CPC",
            price: 0.02,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
        {
            id:12,
            name: "Digicut Production & Advertising",
            symbol: "DIGICUT",
            price: 0.09,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
        {
            id:13,
            name: "Ecobank Ghana Limited",
            symbol: "EGH",
            price: 7,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
        {
            id:14,
            name: "Enterprise Group Limited",
            symbol: "EGL",
            price: 2,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
        {
            id:15,
            name: "Ecobank Transnational Incorporated",
            symbol: "ETI",
            price: 2,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
        {
            id:16,
            name: "Fan Milk Limited",
            symbol: "FML",
            price: 8,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
        {
            id:17,
            name: "GCB Bank Limited",
            symbol: "GCB",
            price: 5.01,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
        {
            id:18,
            name: "Guinness Ghana Breweries Limited",
            symbol: "GCBL",
            price: 2.18,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
        {
            id:19,
            name: "NewGold Issuer Limited",
            symbol: "GLD",
            price: 54,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
        {
            id:20,
            name: "Ghana Oil Company Limited",
            symbol: "GOIL",
            price: 2.36,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
        {
            id:21,
            name: "Golden Star Resources Limited",
            symbol: "GSR",
            price: 9.5,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
        {
            id:22,
            name: "Hords Limited",
            symbol: "HORDS",
            price: 0.1,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
        {
            id:23,
            name: "Intravenous Infusions Limited",
            symbol: "IIL",
            price: 0.08,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
        {
            id:24,
            name: "Mega African Capital Limited",
            symbol: "MAC",
            price: 5.98,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
        {
            id:25,
            name: "Mechanical Lloyd Company Limited",
            symbol: "MLC",
            price: 0.09,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
        {
            id:26,
            name: "Meridian-Marshall Holdings",
            symbol: "MMH",
            price: 0.11,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
        {
            id:27,
            name: "MTN Ghana",
            symbol: "MTNGH",
            price: 0.74,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
        {
            id:28,
            name: "Produce Buying Company Limited",
            symbol: "PBC",
            price: 0.04,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
        {
            id:29,
            name: "PZ Cussons Ghana Limited",
            symbol: "PZC",
            price: 0.4,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
        {
            id:30,
            name: "Republic Bank Ghana Limited",
            symbol: "RGBH",
            price: 0.63,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
        {
            id:31,
            name: "Samba Foods Limited",
            symbol: "SAMBA",
            price: 0.65,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
        {
            id:32,
            name: "Standard Chartered Bank Limited",
            symbol: "SCB",
            price: 21.8,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
        {
            id:33,
            name: "Stanchart Preferential Shares",
            symbol: "SCBPREF",
            price: 0.86,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
        {
            id:34,
            name: "SIC Insurance Company Limited",
            symbol: "SIC",
            price: 0.12,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
        {
            id:35,
            name: "Societe Generale Ghana Limited",
            symbol: "SOGEGH",
            price: 0.72,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
        {
            id:36,
            name: "Starwin Products Limited",
            symbol: "SPL",
            price: 0.03,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
        {
            id:37,
            name: "Sam Woode Limited",
            symbol: "SWL",
            price: 0.05,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
        {
            id:38,
            name: "Trust Bank (Gambia) Limited",
            symbol: "TBL",
            price: 0.2,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
        {
            id:39,
            name: "Tullow Oil Plc",
            symbol: "TLW",
            price: 11.94,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
        {
            id:40,
            name: "Total Petroleum Ghana Limited",
            symbol: "TOTAL",
            price: 4.6,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
        {
            id:41,
            name: "Unilever Ghana Limited",
            symbol: "UNIL",
            price: 17.68,
            assetType:"Stock",
            inCart: false,
            count: 0,
            total:0,
        },
]
