export const investmentAssets = [
    {
        id:1,
        name: "Total Petroleum Ghana",
        symbol: "TOTAL",
        price: 4.61,
        company: "Total Petroleum Ghana",
        assetType:"stock",
        info: "Lorem Ipsum",
        inCart: false,
        count: 0,
        total:0,
    },
    {
        id:2,
        name:"Societe Generale Ghana",
        symbol: "SOGEGH",
        price: 0.98,
        company: "Societe Generale Ghana",
        assetType:"stock",
        info: "Lorem Ipsum",
        inCart: false,
        count: 0,
        total:0,
    },
    {
        id:3,
        name: "Trust Bank",
        symbol: "TBL",
        price: 0.83,
        company: "Trust Bank",
        assetType: "stock",
        info: "Lorem Ipsum",
        inCart: false,
        count: 0,
        total:0,
    },
    {
        id:4,
        name: "Ghana Government Bond",
        symbol: "GHB",
        price: 50.02,
        company: "Ghana Government",
        assetType:"bond",
        info: "Lorem Ipsum",
        inCart: false,
        count: 0,
        total:0,
    },
    {
        id:5,
        name: "Coca Cola Private Bonds",
        symbol: "CCBL",
        price: 34.54,
        company: "Coca Cola Ghana",
        assetType:"bond",
        info: "Lorem Ipsum",
        inCart: false,
        count: 0,
        total:0,
    },
]
